import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'
import { defineConfig } from 'vitepress'
import { exampleSourcePlugin } from '../lib/example-source.js'
import { EXAMPLE_ORDER } from '../lib/examples-order.js'

// GitHub Pages serves the site under `/egui-react/`, the Cloudflare preview
// under `/`; `site/build.sh` passes whichever applies. A trailing slash is
// what VitePress and `withBase` expect.
const base = process.env.SITE_BASE ?? '/'

const SITE = path.dirname(fileURLToPath(import.meta.url))


/// The names the old gallery deep links can carry, taken from the pages that
/// exist rather than from a second list.
const pages = new Set(
  fs
    .readdirSync(path.join(SITE, '..', 'examples'))
    .filter((file) => file.endsWith('.md'))
    .map((file) => file.slice(0, -'.md'.length))
)
const known = EXAMPLE_ORDER.filter((name) => pages.has(name))

/// `https://fand.github.io/egui-react/#counter` was the gallery; it is now an
/// example page. Inline in `head` so it runs before the router hydrates and the
/// reader never sees the home page flash by.
const redirect = `
(function () {
  var base = ${JSON.stringify(base)};
  var names = ${JSON.stringify(known)};
  var path = location.pathname;
  if (path !== base && path !== base + 'index.html') return;
  var match = /^#([a-z0-9-]+)(\\/plain)?$/.exec(location.hash);
  if (!match) return;
  // The example was called showcase until September 2026; old links still work.
  var name = match[1] === 'showcase' ? 'notes' : match[1];
  if (names.indexOf(name) !== -1) {
    location.replace(base + 'examples/' + name + '.html');
  }
})();
`.trim()

export default defineConfig({
  title: 'egui-react',
  description:
    'Write egui applications the way you write React: an rsx! macro, function components and hooks.',
  base,
  lang: 'en-US',
  cleanUrls: false,
  // A link to a page that is not there is a bug in the docs, not something to
  // find in production; this is VitePress's default and stays on.
  ignoreDeadLinks: false,
  head: [['script', {}, redirect]],
  // An example page is the running example beside its code, the way the
  // gallery laid them out (`theme/ExamplePage.vue`): the whole content area,
  // no outline aside. Set here rather than in seventeen frontmatter blocks so
  // a new page gets it by being in the directory. `shell` has no running
  // example and stays an ordinary page, and so does the Examples index.
  transformPageData(pageData) {
    if (
      pageData.relativePath.startsWith('examples/') &&
      pageData.relativePath !== 'examples/index.md' &&
      pageData.relativePath !== 'examples/shell.md'
    ) {
      pageData.frontmatter.aside = false
      pageData.frontmatter.outline = false
      pageData.frontmatter.pageClass = 'example-page'
    }
  },
  markdown: {
    config: (md) => {
      md.use(exampleSourcePlugin)
    }
  },
  themeConfig: {
    // No server to run a query against: the whole index ships with the site.
    search: { provider: 'local' },
    nav: [
      { text: 'Guide', link: '/guide/rsx' },
      { text: 'Reference', link: '/reference/hooks' },
      { text: 'Examples', link: '/examples/' },
      // rustdoc, generated by cargo into the same dist and not a VitePress
      // route: `target` keeps the single-page router from trying to resolve it.
      { text: 'API', link: '/api/', target: '_blank', rel: 'noreferrer' }
    ],
    socialLinks: [{ icon: 'github', link: 'https://github.com/fand/egui-react' }],
    sidebar: [
      {
        text: 'Introduction',
        items: [
          { text: 'Getting Started', link: '/getting-started' },
          { text: 'How it works', link: '/how-it-works' }
        ]
      },
      {
        text: 'Guide',
        items: [
          { text: 'rsx!', link: '/guide/rsx' },
          { text: 'Components and events', link: '/guide/components-and-events' },
          { text: 'State and hooks', link: '/guide/state-and-hooks' },
          { text: 'Layout', link: '/guide/layout' },
          { text: 'Async', link: '/guide/async' },
          { text: 'Escape hatches', link: '/guide/escape-hatches' },
          { text: 'Fonts', link: '/guide/fonts' },
          { text: 'Web and native', link: '/guide/web-and-native' }
        ]
      },
      {
        text: 'Reference',
        items: [
          { text: 'Hooks', link: '/reference/hooks' },
          { text: 'Elements', link: '/reference/elements' },
          { text: 'Layout attributes', link: '/reference/layout-attributes' }
        ]
      },
      {
        text: 'Examples',
        collapsed: false,
        items: [
          { text: 'All examples', link: '/examples/' },
          ...EXAMPLE_ORDER.map((name) => ({ text: name, link: `/examples/${name}` }))
        ]
      },
      {
        text: 'Project',
        items: [{ text: 'Architecture', link: '/architecture' }]
      }
    ],
    editLink: {
      pattern: 'https://github.com/fand/egui-react/edit/main/site/:path',
      text: 'Edit this page on GitHub'
    },
    footer: {
      message: 'Released under the MIT or Apache-2.0 license.',
      copyright: 'egui-react'
    }
  }
})
