import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'
import { defineConfig } from 'vitepress'
import { exampleSourcePlugin } from '../lib/example-source.js'
import { EXAMPLE_ORDER } from '../lib/examples-order.js'

// GitHub Pages serves the site under `/egui-react/`, the Cloudflare preview
// under `/`; `site/build.sh` passes whichever applies. A trailing slash is
// what VitePress and `withBase` expect.
const base = process.env.SITE_BASE ?? '/'

const SITE = path.dirname(fileURLToPath(import.meta.url))


/// The names the old gallery deep links can carry, taken from the pages that
/// exist rather than from a second list.
const pages = new Set(
  fs
    .readdirSync(path.join(SITE, '..', 'examples'))
    .filter((file) => file.endsWith('.md'))
    .map((file) => file.slice(0, -'.md'.length))
)
const known = EXAMPLE_ORDER.filter((name) => pages.has(name))

/// `https://fand.github.io/egui-react/#counter` was the gallery; it is now an
/// example page. Inline in `head` so it runs before the router hydrates and the
/// reader never sees the home page flash by.
const redirect = `
(function () {
  var base = ${JSON.stringify(base)};
  var names = ${JSON.stringify(known)};
  var path = location.pathname;
  if (path !== base && path !== base + 'index.html') return;
  var match = /^#([a-z0-9-]+)(\\/plain)?$/.exec(location.hash);
  if (!match) return;
  // The example was called showcase until September 2026; old links still work.
  var name = match[1] === 'showcase' ? 'notes' : match[1];
  if (names.indexOf(name) !== -1) {
    location.replace(base + 'examples/' + name + '.html');
  }
})();
`.trim()

/// The English page titles, by path. The Japanese locale gives the same keys
/// its own titles, so the two navigations cannot fall out of step: a page
/// added to one shows up missing in the other.
const EN = {
  nav: { guide: 'Guide', reference: 'Reference', examples: 'Examples', api: 'API' },
  groups: {
    intro: 'Introduction',
    guide: 'Guide',
    reference: 'Reference',
    examples: 'Examples',
    project: 'Project'
  },
  pages: {
    'getting-started': 'Getting Started',
    'how-it-works': 'How it works',
    'guide/rsx': 'rsx!',
    'guide/components-and-events': 'Components and events',
    'guide/state-and-hooks': 'State and hooks',
    'guide/layout': 'Layout',
    'guide/async': 'Async',
    'guide/escape-hatches': 'Escape hatches',
    'guide/fonts': 'Fonts',
    'guide/web-and-native': 'Web and native',
    'reference/hooks': 'Hooks',
    'reference/elements': 'Elements',
    'reference/layout-attributes': 'Layout attributes',
    architecture: 'Architecture'
  }
}

const JA = {
  nav: { guide: 'ガイド', reference: 'リファレンス', examples: 'サンプル', api: 'API' },
  groups: {
    intro: 'はじめに',
    guide: 'ガイド',
    reference: 'リファレンス',
    examples: 'サンプル',
    project: 'プロジェクト'
  },
  pages: {
    'getting-started': 'はじめる',
    'how-it-works': '仕組み',
    'guide/rsx': 'rsx!',
    'guide/components-and-events': 'コンポーネントとイベント',
    'guide/state-and-hooks': '状態とフック',
    'guide/layout': 'レイアウト',
    'guide/async': '非同期',
    'guide/escape-hatches': 'エスケープハッチ',
    'guide/fonts': 'フォント',
    'guide/web-and-native': 'Web とネイティブ',
    'reference/hooks': 'フック',
    'reference/elements': '要素',
    'reference/layout-attributes': 'レイアウト属性',
    architecture: 'アーキテクチャ'
  }
}

/// One locale's navigation. `prefix` is `''` for English at the site root and
/// `/ja` for the translation; every link is written once, here, so a new page
/// is one entry per language and nothing else.
function nav(prefix: string, t: typeof EN) {
  return [
    { text: t.nav.guide, link: `${prefix}/guide/rsx` },
    { text: t.nav.reference, link: `${prefix}/reference/hooks` },
    { text: t.nav.examples, link: `${prefix}/examples/` },
    // rustdoc, generated by cargo into the same dist and not a VitePress
    // route: `target` keeps the single-page router from trying to resolve it.
    // English only, because rustdoc is what the crates' own comments say.
    { text: t.nav.api, link: '/api/', target: '_blank', rel: 'noreferrer' }
  ]
}

function sidebar(prefix: string, t: typeof EN) {
  const item = (page: keyof typeof EN.pages) => ({
    text: t.pages[page],
    link: `${prefix}/${page}`
  })
  return [
    { text: t.groups.intro, items: [item('getting-started'), item('how-it-works')] },
    {
      text: t.groups.guide,
      items: [
        item('guide/rsx'),
        item('guide/components-and-events'),
        item('guide/state-and-hooks'),
        item('guide/layout'),
        item('guide/async'),
        item('guide/escape-hatches'),
        item('guide/fonts'),
        item('guide/web-and-native')
      ]
    },
    {
      text: t.groups.reference,
      items: [
        item('reference/hooks'),
        item('reference/elements'),
        item('reference/layout-attributes')
      ]
    },
    {
      text: t.groups.examples,
      // The group's own title is the link to the Examples page, the one
      // with a card per example.
      link: `${prefix}/examples/`,
      collapsed: false,
      // An example's name is its directory name in both languages: it is what
      // `cargo run -p <name>` takes.
      items: EXAMPLE_ORDER.map((name) => ({ text: name, link: `${prefix}/examples/${name}` }))
    },
    { text: t.groups.project, items: [item('architecture')] }
  ]
}

export default defineConfig({
  title: 'egui-reactor',
  description:
    'Write egui applications the way you write React: an rsx! macro, function components and hooks.',
  base,
  cleanUrls: false,
  // A link to a page that is not there is a bug in the docs, not something to
  // find in production; this is VitePress's default and stays on.
  ignoreDeadLinks: false,
  head: [
    // Served from `public/`, so the path needs the same base as the pages;
    // `head` is written out as-is and nothing resolves it for us.
    ['link', { rel: 'icon', type: 'image/svg+xml', href: `${base}atomic-ferris-icon.svg` }],
    ['script', {}, redirect]
  ],
  // English at the site root, Japanese under `/ja/`. The pages themselves are
  // `site/*.md` and `site/ja/*.md`, the same tree twice: VitePress maps a
  // locale key to the directory of that name, so `site/ja/guide/rsx.md` is
  // `/ja/guide/rsx.html` and the language menu can pair the two.
  locales: {
    root: {
      label: 'English',
      lang: 'en-US',
      themeConfig: { nav: nav('', EN), sidebar: sidebar('', EN) }
    },
    ja: {
      label: '日本語',
      lang: 'ja',
      link: '/ja/',
      description:
        'React を書くように egui アプリを書く: rsx! マクロ、関数コンポーネント、フック。',
      themeConfig: {
        nav: nav('/ja', JA),
        sidebar: sidebar('/ja', JA),
        editLink: {
          pattern: 'https://github.com/fand/egui-react/edit/main/site/:path',
          text: 'このページを GitHub で編集する'
        },
        outline: { label: '目次' },
        docFooter: { prev: '前のページ', next: '次のページ' },
        lastUpdatedText: '最終更新',
        darkModeSwitchLabel: '外観',
        lightModeSwitchTitle: 'ライトテーマに切り替える',
        darkModeSwitchTitle: 'ダークテーマに切り替える',
        sidebarMenuLabel: 'メニュー',
        returnToTopLabel: 'トップへ戻る',
        langMenuLabel: '言語を変更する',
        footer: {
          message: 'MIT または Apache-2.0 ライセンスで公開しています。',
          copyright: 'egui-reactor'
        }
      }
    }
  },
  // An example page is the running example beside its code, the way the
  // gallery laid them out (`theme/ExamplePage.vue`): the whole content area,
  // no outline aside. Set here rather than in seventeen frontmatter blocks so
  // a new page gets it by being in the directory. The Examples index is an
  // ordinary page. `ja/` pages take the same treatment.
  transformPageData(pageData) {
    const page = pageData.relativePath.replace(/^ja\//, '')
    if (page.startsWith('examples/') && page !== 'examples/index.md') {
      pageData.frontmatter.aside = false
      pageData.frontmatter.outline = false
      pageData.frontmatter.pageClass = 'example-page'
    }
  },
  markdown: {
    config: (md) => {
      md.use(exampleSourcePlugin)
    }
  },
  themeConfig: {
    // Left of the site title in the nav bar, on every page and in both
    // languages. VitePress resolves the path against `base` itself. The icon
    // is the mark drawn for this size: twice the stroke, two balls parked,
    // no animation — the hero's own file disappears at 24px.
    logo: '/atomic-ferris-icon.svg',
    // No server to run a query against: the whole index ships with the site.
    // One index per locale, so a Japanese search does not answer in English.
    search: {
      provider: 'local',
      options: {
        locales: {
          ja: {
            translations: {
              button: { buttonText: '検索', buttonAriaLabel: '検索' },
              modal: {
                displayDetails: '詳細を表示',
                resetButtonTitle: '検索をリセット',
                backButtonTitle: '戻る',
                noResultsText: '見つかりません:',
                footer: {
                  selectText: '選択',
                  selectKeyAriaLabel: 'Enter',
                  navigateText: '移動',
                  navigateUpKeyAriaLabel: '上矢印',
                  navigateDownKeyAriaLabel: '下矢印',
                  closeText: '閉じる',
                  closeKeyAriaLabel: 'Esc'
                }
              }
            }
          }
        }
      }
    },
    socialLinks: [{ icon: 'github', link: 'https://github.com/fand/egui-react' }],
    editLink: {
      pattern: 'https://github.com/fand/egui-react/edit/main/site/:path',
      text: 'Edit this page on GitHub'
    },
    footer: {
      message: 'Released under the MIT or Apache-2.0 license.',
      copyright: 'egui-reactor'
    }
  }
})
