import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'
import { defineConfig } from 'vitepress'
import { exampleSourcePlugin } from '../lib/example-source.js'

// GitHub Pages serves the site under `/egui-react/`, the Cloudflare preview
// under `/`; `site/build.sh` passes whichever applies. A trailing slash is
// what VitePress and `withBase` expect.
const base = process.env.SITE_BASE ?? '/'

const SITE = path.dirname(fileURLToPath(import.meta.url))

/// The example pages, in the gallery's order: the sidebar and the redirect
/// below are both built from this, so a page that is added or renamed needs no
/// second edit here.
const EXAMPLES = [
  'showcase',
  'board',
  'patch',
  'spreadsheet',
  'counter',
  'todo',
  'form',
  'theme',
  'clock',
  'custom-hook',
  'escape-hatch',
  'shader',
  'list-10k',
  'layout',
  'styles',
  'fetch',
  'font',
  // Not in the gallery's `EXAMPLES`: a docked panel carves up the window, so
  // there is nothing an embed could do with it. The page is code only.
  'shell'
]

/// The names the old gallery deep links can carry, taken from the pages that
/// exist rather than from a second list.
const pages = new Set(
  fs
    .readdirSync(path.join(SITE, '..', 'examples'))
    .filter((file) => file.endsWith('.md'))
    .map((file) => file.slice(0, -'.md'.length))
)
const known = EXAMPLES.filter((name) => pages.has(name))

/// `https://fand.github.io/egui-react/#counter` was the gallery; it is now an
/// example page. Inline in `head` so it runs before the router hydrates and the
/// reader never sees the home page flash by.
const redirect = `
(function () {
  var base = ${JSON.stringify(base)};
  var names = ${JSON.stringify(known)};
  var path = location.pathname;
  if (path !== base && path !== base + 'index.html') return;
  var match = /^#([a-z0-9-]+)(\\/plain)?$/.exec(location.hash);
  if (match && names.indexOf(match[1]) !== -1) {
    location.replace(base + 'examples/' + match[1] + '.html');
  }
})();
`.trim()

export default defineConfig({
  title: 'egui-react',
  description:
    'Write egui applications the way you write React: an rsx! macro, function components and hooks.',
  base,
  lang: 'en-US',
  cleanUrls: false,
  // A link to a page that is not there is a bug in the docs, not something to
  // find in production; this is VitePress's default and stays on.
  ignoreDeadLinks: false,
  head: [['script', {}, redirect]],
  markdown: {
    config: (md) => {
      md.use(exampleSourcePlugin)
    }
  },
  themeConfig: {
    // No server to run a query against: the whole index ships with the site.
    search: { provider: 'local' },
    nav: [
      { text: 'Guide', link: '/guide/thinking-in-egui-react' },
      { text: 'Reference', link: '/reference/hooks' },
      { text: 'Examples', link: '/examples/counter' },
      // rustdoc, generated by cargo into the same dist and not a VitePress
      // route: `target` keeps the single-page router from trying to resolve it.
      { text: 'API', link: '/api/', target: '_blank', rel: 'noreferrer' }
    ],
    socialLinks: [{ icon: 'github', link: 'https://github.com/fand/egui-react' }],
    sidebar: [
      {
        text: 'Introduction',
        items: [
          { text: 'What is egui-react?', link: '/' },
          { text: 'Getting Started', link: '/getting-started' }
        ]
      },
      {
        text: 'Guide',
        items: [
          { text: 'Thinking in egui-react', link: '/guide/thinking-in-egui-react' },
          { text: 'rsx!', link: '/guide/rsx' },
          { text: 'Components and events', link: '/guide/components-and-events' },
          { text: 'State and hooks', link: '/guide/state-and-hooks' },
          { text: 'Layout', link: '/guide/layout' },
          { text: 'Async', link: '/guide/async' },
          { text: 'Escape hatches', link: '/guide/escape-hatches' },
          { text: 'Fonts', link: '/guide/fonts' },
          { text: 'Web and native', link: '/guide/web-and-native' }
        ]
      },
      {
        text: 'Reference',
        items: [
          { text: 'Hooks', link: '/reference/hooks' },
          { text: 'Elements', link: '/reference/elements' },
          { text: 'Layout attributes', link: '/reference/layout-attributes' }
        ]
      },
      {
        text: 'Examples',
        collapsed: false,
        items: EXAMPLES.map((name) => ({ text: name, link: `/examples/${name}` }))
      },
      {
        text: 'Project',
        items: [{ text: 'Architecture', link: '/architecture' }]
      }
    ],
    editLink: {
      pattern: 'https://github.com/fand/egui-react/edit/main/site/:path',
      text: 'Edit this page on GitHub'
    },
    footer: {
      message: 'Released under the MIT or Apache-2.0 license.',
      copyright: 'egui-react'
    }
  }
})
