[package]
name = "counter"
description = "egui-react example: counter"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
publish = false

[lib]
name = "counter"
path = "src/lib.rs"

[[bin]]
name = "counter"
path = "src/main.rs"

[[bin]]
name = "counter-plain"
path = "src/plain_main.rs"

[dependencies]
eframe.workspace = true
egui.workspace = true
egui-react.workspace = true
egui-react-app.workspace = true
egui-react-elements.workspace = true
example-meta.workspace = true

[dev-dependencies]
egui_kittest.workspace = true
