[package]
name = "form"
description = "egui-reactor example: form"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
publish = false

[lib]
name = "form"
path = "src/lib.rs"

[[bin]]
name = "form"
path = "src/main.rs"

[[bin]]
name = "form-plain"
path = "src/plain_main.rs"

[dependencies]
eframe.workspace = true
egui.workspace = true
egui-reactor.workspace = true
egui-reactor-app.workspace = true
egui-reactor-elements.workspace = true
example-meta.workspace = true
serde.workspace = true
serde_json.workspace = true

[dev-dependencies]
egui_kittest.workspace = true
