[package]
name = "spike"
description = "Spike example for react-egui"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
publish = false

[[bin]]
name = "spike"
path = "src/main.rs"

[dependencies]
eframe.workspace = true
egui.workspace = true
react-egui.workspace = true
