//! `#[component]`: props struct, event enum and the `(cx, props)` function.

use proc_macro2::{Span, TokenStream};
use quote::{format_ident, quote};
use syn::spanned::Spanned;
use syn::visit::Visit;
use syn::visit_mut::VisitMut;

use crate::util::{arg_ident, event_variant_name, is_cx_ref, is_option, to_compile_error};

/// The lifetime every elided reference in a prop is rewritten to.
const PROP_LIFETIME: &str = "'__react_egui_e";

pub(crate) fn expand(attr: TokenStream, item: TokenStream) -> TokenStream {
    match try_expand(attr, item.clone()) {
        Ok(tokens) => tokens,
        // Keep the original item so the rest of the file still resolves.
        Err(err) => {
            let err = to_compile_error(err);
            quote! { #item #err }
        }
    }
}

/// What `#[prop(..)]` asked for on one argument.
#[derive(Default)]
struct PropAttr {
    /// `Some(None)` for `default`, `Some(Some(e))` for `default = e`.
    default: Option<Option<syn::Expr>>,
    into: bool,
}

/// One declared argument, after the argument attributes have been digested.
struct Prop {
    name: syn::Ident,
    ty: syn::Type,
    attr: PropAttr,
    /// Set for `#[event] on_x: Payload`.
    event_variant: Option<syn::Ident>,
}

fn try_expand(attr: TokenStream, item: TokenStream) -> syn::Result<TokenStream> {
    if !attr.is_empty() {
        return Err(syn::Error::new_spanned(
            attr,
            "react-egui: #[component] takes no arguments",
        ));
    }
    let function: syn::ItemFn = syn::parse2(item)?;
    check_returns_nothing(&function)?;

    let (cx, cx_ty) = cx_argument(&function)?;
    let (props, impl_params) = collect_props(&function)?;

    let name = &function.sig.ident;
    let vis = &function.vis;
    let props_ident = format_ident!("{}Props", name);
    let event_ident = format_ident!("{}Event", name);
    let builder_ident = format_ident!("{}PropsBuilder", name);

    let events: Vec<&Prop> = props.iter().filter(|p| p.event_variant.is_some()).collect();
    let has_events = !events.is_empty();
    let fields: Vec<&Prop> = props.iter().filter(|p| p.event_variant.is_none()).collect();
    let declares_children = fields.iter().any(|p| p.name == "children");

    // `'e` is only declared when a prop or the events field actually uses it.
    let uses_prop_lifetime = has_events || fields.iter().any(|p| mentions_prop_lifetime(&p.ty));

    let generics = props_generics(&function, uses_prop_lifetime, &impl_params);
    let (impl_generics, ty_generics, where_clause) = generics.split_for_impl();
    let builder_ty = builder_type(&builder_ident, &generics);
    let prop_lifetime = syn::Lifetime::new(PROP_LIFETIME, Span::call_site());

    // The event enum only carries the generics its payload types actually use.
    let event_generics = used_generics(&generics, events.iter().map(|p| &p.ty));
    let (event_impl_generics, event_ty_generics, _) = event_generics.split_for_impl();
    let event_ty = quote!(#event_ident #event_ty_generics);

    let event_enum = has_events.then(|| {
        let variants = events.iter().map(|p| {
            let variant = p.event_variant.as_ref().expect("filtered");
            let ty = &p.ty;
            quote! { #variant(#ty) }
        });
        let doc = format!(
            "Events emitted by [`{name}`]. Generated by `#[component]`; \
             `rsx!` needs this name in scope wherever `<{name} on_../>` is written."
        );
        quote! {
            #[doc = #doc]
            #[allow(dead_code)]
            #vis enum #event_ident #event_impl_generics { #(#variants),* }
        }
    });

    let field_decls = fields.iter().map(|prop| {
        let name = &prop.name;
        let ty = &prop.ty;
        let builder_attr = builder_attr_for(prop);
        let doc = format!("The `{name}` prop.");
        quote! { #[doc = #doc] #builder_attr pub #name: #ty }
    });
    let events_field = has_events.then(|| {
        quote! {
            /// The parent's fused event closure; `rsx!` fills this in.
            #[builder(default, setter(strip_option))]
            pub events: ::core::option::Option<
                &#prop_lifetime mut (dyn ::core::ops::FnMut(#event_ty) + #prop_lifetime)
            >,
        }
    });
    let generated_children = (!declares_children).then(|| {
        quote! {
            /// Always present, because `rsx!` always passes children.
            #[builder(default)]
            pub children: (),
        }
    });

    let field_names = fields.iter().map(|p| &p.name);
    let destructure_events = has_events.then(|| quote!(events,));
    let destructure_children = (!declares_children).then(|| quote!(children: _,));

    let event_prologue = has_events.then(|| {
        let emitters = events.iter().map(|p| {
            let name = &p.name;
            let variant = p.event_variant.as_ref().expect("filtered");
            quote! {
                let #name =
                    ::react_egui::Emitter::new(&__react_egui_sink, #event_ident::#variant);
            }
        });
        quote! {
            let mut __react_egui_noop = |_: #event_ty| {};
            // The `match` arms shorten `'e` down to this body.
            let __react_egui_events: &mut dyn ::core::ops::FnMut(#event_ty) = match events {
                ::core::option::Option::Some(events) => events,
                ::core::option::Option::None => &mut __react_egui_noop,
            };
            let __react_egui_sink = ::react_egui::EventSink::new(__react_egui_events);
            #(#emitters)*
        }
    });

    let body = show_tail(&function.block, &cx);
    let attrs = &function.attrs;
    let props_doc = format!("Props for [`{name}`]. Generated by `#[component]`.");

    Ok(quote! {
        #event_enum

        #[doc = #props_doc]
        #[derive(::react_egui::__private::TypedBuilder)]
        #[builder(crate_module_path = ::react_egui::__private::typed_builder)]
        #vis struct #props_ident #impl_generics #where_clause {
            #(#field_decls,)*
            #events_field
            #generated_children
        }

        #[automatically_derived]
        impl #impl_generics ::react_egui::__private::Props for #props_ident #ty_generics
        #where_clause
        {
            type Builder = #builder_ty;
            fn builder() -> Self::Builder {
                <#props_ident #ty_generics>::builder()
            }
        }

        #(#attrs)*
        #[allow(non_snake_case)]
        #vis fn #name #impl_generics (
            #cx: #cx_ty,
            __react_egui_props: #props_ident #ty_generics,
        ) #where_clause {
            let #props_ident {
                #(#field_names,)*
                #destructure_events
                #destructure_children
            } = __react_egui_props;
            #event_prologue
            #body
        }
    })
}

/// `-> ()` or nothing; anything else is an error.
fn check_returns_nothing(function: &syn::ItemFn) -> syn::Result<()> {
    if let syn::ReturnType::Type(_, ty) = &function.sig.output
        && !matches!(&**ty, syn::Type::Tuple(t) if t.elems.is_empty())
    {
        return Err(syn::Error::new_spanned(
            ty,
            "react-egui: a #[component] function returns nothing; put the view in \
             the body's tail expression instead of returning it",
        ));
    }
    Ok(())
}

/// The name and type of the mandatory first `cx: &mut Cx` argument.
fn cx_argument(function: &syn::ItemFn) -> syn::Result<(syn::Ident, syn::Type)> {
    match function.sig.inputs.first() {
        Some(syn::FnArg::Typed(arg)) if is_cx_ref(&arg.ty) => {
            Ok((arg_ident(arg)?, (*arg.ty).clone()))
        }
        Some(other) => Err(syn::Error::new(
            other.span(),
            "react-egui: the first argument of a #[component] function must be `cx: &mut Cx`",
        )),
        None => Err(syn::Error::new(
            function.sig.span(),
            "react-egui: a #[component] function must take `cx: &mut Cx` as its first argument",
        )),
    }
}

/// Every argument after `cx`, plus the type parameters `impl Trait` desugared to.
fn collect_props(function: &syn::ItemFn) -> syn::Result<(Vec<Prop>, Vec<syn::TypeParam>)> {
    let mut impl_params: Vec<syn::TypeParam> = Vec::new();
    let mut props = Vec::new();
    for arg in function.sig.inputs.iter().skip(1) {
        let syn::FnArg::Typed(arg) = arg else {
            return Err(syn::Error::new(
                arg.span(),
                "react-egui: a #[component] function cannot take `self`",
            ));
        };
        let name = arg_ident(arg)?;
        let (attr, is_event) = parse_arg_attrs(&arg.attrs)?;
        let mut ty = (*arg.ty).clone();
        ElideToPropLifetime.visit_type_mut(&mut ty);
        if let syn::Type::ImplTrait(imp) = &ty {
            let ident = format_ident!("TProp{}", impl_params.len());
            let bounds = &imp.bounds;
            impl_params.push(syn::parse_quote!(#ident: #bounds));
            ty = syn::parse_quote!(#ident);
        }
        let event_variant =
            is_event.then(|| syn::Ident::new(&event_variant_name(&name.to_string()), name.span()));
        props.push(Prop {
            name,
            ty,
            attr,
            event_variant,
        });
    }
    Ok((props, impl_params))
}

/// `<'e, ..the function's own params.., ..impl Trait params..>`.
fn props_generics(
    function: &syn::ItemFn,
    uses_prop_lifetime: bool,
    impl_params: &[syn::TypeParam],
) -> syn::Generics {
    let mut generics = syn::Generics::default();
    if uses_prop_lifetime {
        let lifetime = syn::Lifetime::new(PROP_LIFETIME, Span::call_site());
        generics.params.push(syn::parse_quote!(#lifetime));
    }
    for param in &function.sig.generics.params {
        generics.params.push(param.clone());
    }
    for param in impl_params {
        generics.params.push(syn::GenericParam::Type(param.clone()));
    }
    generics.where_clause = function.sig.generics.where_clause.clone();
    generics
}

/// `NamePropsBuilder<'e, C>`: the parameters again, without their bounds.
///
/// typed-builder's extra `TypedBuilderFields` parameter defaults to the
/// all-unset tuple, so it does not have to be named here.
fn builder_type(builder_ident: &syn::Ident, generics: &syn::Generics) -> TokenStream {
    let args: Vec<TokenStream> = generics
        .params
        .iter()
        .map(|param| match param {
            syn::GenericParam::Lifetime(l) => {
                let lifetime = &l.lifetime;
                quote!(#lifetime)
            }
            syn::GenericParam::Type(t) => {
                let ident = &t.ident;
                quote!(#ident)
            }
            syn::GenericParam::Const(c) => {
                let ident = &c.ident;
                quote!(#ident)
            }
        })
        .collect();
    if args.is_empty() {
        quote!(#builder_ident)
    } else {
        quote!(#builder_ident<#(#args),*>)
    }
}

/// The subset of `generics` that `types` actually mention, in the same order.
///
/// An enum cannot declare a parameter it does not use, so the event enum takes
/// only what its payload types need.
fn used_generics<'a>(
    generics: &syn::Generics,
    types: impl Iterator<Item = &'a syn::Type>,
) -> syn::Generics {
    #[derive(Default)]
    struct Used {
        lifetimes: Vec<String>,
        types: Vec<String>,
    }
    impl<'ast> Visit<'ast> for Used {
        fn visit_lifetime(&mut self, node: &'ast syn::Lifetime) {
            self.lifetimes.push(node.ident.to_string());
        }
        fn visit_path(&mut self, node: &'ast syn::Path) {
            if let Some(ident) = node.get_ident() {
                self.types.push(ident.to_string());
            }
            syn::visit::visit_path(self, node);
        }
    }
    let mut used = Used::default();
    for ty in types {
        used.visit_type(ty);
    }

    let mut out = syn::Generics::default();
    for param in &generics.params {
        let keep = match param {
            syn::GenericParam::Lifetime(l) => {
                used.lifetimes.contains(&l.lifetime.ident.to_string())
            }
            syn::GenericParam::Type(t) => used.types.contains(&t.ident.to_string()),
            syn::GenericParam::Const(c) => used.types.contains(&c.ident.to_string()),
        };
        if keep {
            out.params.push(param.clone());
        }
    }
    out
}

/// Rewrite `&T` into `&'__react_egui_e T` so the props struct can hold it.
struct ElideToPropLifetime;

impl VisitMut for ElideToPropLifetime {
    fn visit_type_reference_mut(&mut self, node: &mut syn::TypeReference) {
        if node.lifetime.is_none() {
            node.lifetime = Some(syn::Lifetime::new(PROP_LIFETIME, node.and_token.span));
        }
        syn::visit_mut::visit_type_reference_mut(self, node);
    }

    fn visit_lifetime_mut(&mut self, node: &mut syn::Lifetime) {
        if node.ident == "_" {
            *node = syn::Lifetime::new(PROP_LIFETIME, node.apostrophe);
        }
    }
}

/// Does this type mention `'__react_egui_e`?
fn mentions_prop_lifetime(ty: &syn::Type) -> bool {
    struct Finder(bool);
    impl<'ast> Visit<'ast> for Finder {
        fn visit_lifetime(&mut self, node: &'ast syn::Lifetime) {
            if node.to_string() == PROP_LIFETIME {
                self.0 = true;
            }
        }
    }
    let mut finder = Finder(false);
    finder.visit_type(ty);
    finder.0
}

/// The `#[builder(..)]` attribute for one prop.
fn builder_attr_for(prop: &Prop) -> Option<TokenStream> {
    let mut parts: Vec<TokenStream> = Vec::new();
    match &prop.attr.default {
        Some(Some(expr)) => parts.push(quote!(default = #expr)),
        Some(None) => parts.push(quote!(default)),
        // `Option<T>` props are optional without asking.
        None if is_option(&prop.ty) => parts.push(quote!(default)),
        None => {}
    }
    if prop.attr.into {
        parts.push(quote!(setter(into)));
    }
    (!parts.is_empty()).then(|| quote! { #[builder(#(#parts),*)] })
}

/// Read `#[prop(..)]` / `#[event]` off one argument.
fn parse_arg_attrs(attrs: &[syn::Attribute]) -> syn::Result<(PropAttr, bool)> {
    let mut prop = PropAttr::default();
    let mut is_event = false;
    for attr in attrs {
        if attr.path().is_ident("event") {
            attr.meta.require_path_only().map_err(|_| {
                syn::Error::new_spanned(attr, "react-egui: #[event] takes no arguments")
            })?;
            is_event = true;
        } else if attr.path().is_ident("prop") {
            attr.parse_nested_meta(|meta| {
                if meta.path.is_ident("default") {
                    if meta.input.peek(syn::Token![=]) {
                        prop.default = Some(Some(meta.value()?.parse()?));
                    } else {
                        prop.default = Some(None);
                    }
                    Ok(())
                } else if meta.path.is_ident("into") {
                    prop.into = true;
                    Ok(())
                } else {
                    Err(meta.error(
                        "react-egui: unknown #[prop(..)] option (expected `default` or `into`)",
                    ))
                }
            })?;
        } else {
            return Err(syn::Error::new_spanned(
                attr,
                "react-egui: unknown attribute on a #[component] argument \
                 (expected #[prop(..)] or #[event])",
            ));
        }
    }
    Ok((prop, is_event))
}

/// Rewrite the body's tail expression into `View::show(tail, cx);`.
///
/// Wrapping the whole block instead would make the borrows the block's locals
/// hold outlive it, which does not compile.
fn show_tail(block: &syn::Block, cx: &syn::Ident) -> TokenStream {
    let mut block = block.clone();
    let tail: Option<TokenStream> = match block.stmts.last() {
        Some(syn::Stmt::Expr(expr, None)) => Some(quote!(#expr)),
        // A braced macro call in tail position (`rsx! { .. }`) parses as a
        // statement macro, not an expression.
        Some(syn::Stmt::Macro(mac)) if mac.semi_token.is_none() => {
            let mac = &mac.mac;
            Some(quote!(#mac))
        }
        _ => None,
    };
    if let Some(tail) = tail {
        block.stmts.pop();
        block
            .stmts
            .push(syn::parse_quote!(::react_egui::View::show(#tail, #cx);));
    }
    quote! { #block }
}
