[package]
name = "todo"
description = "react-egui example: todo"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
publish = false

[lib]
name = "todo"
path = "src/lib.rs"

[[bin]]
name = "todo"
path = "src/main.rs"

[dependencies]
eframe.workspace = true
egui.workspace = true
react-egui.workspace = true
react-egui-app.workspace = true
react-egui-elements.workspace = true
example-meta.workspace = true
serde.workspace = true
