[package]
name = "react-egui-elements"
description = "Placeholder crate for react-egui elements"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[lib]
name = "react_egui_elements"
path = "src/lib.rs"

[dependencies]
